spring.application.name=portfolio

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=david
spring.datasource.password=21081990

# Configuraciones Hakari
# Maximo de conecciones fisicas a la base de datos
spring.datasource.hikari.maximum-pool-size=10
# Tiempo maximo de espera para que se asigne una conexión a la base de datos
spring.datasource.hikari.connection-timeout=20000

# Crear las tablas e insertar los datos en las tabkas cada que el proyecto se inicie
spring.sql.init.mode=always