server.port=9090
spring.application.name=portfolio

# Database
spring.datasource.url=jdbc:postgresql://dav-devops.com:5432/portfolio
spring.datasource.username=david
spring.datasource.password=21081990

# Configuraciones Hakari
# Maximo de conecciones fisicas a la base de datos
spring.datasource.hikari.maximum-pool-size=10
# Tiempo maximo de espera para que se asigne una conexión a la base de datos
spring.datasource.hikari.connection-timeout=20000

# Ejecutar schema.sql/data.sql solo si la BD está vacía (embedded).
# Usa "always" solo si quieres recrear tablas en cada arranque (BD de desarrollo).
spring.sql.init.mode=never